### ISSUE TITLE
TypeError: column.getSQLType is not a function

### ISSUE THREAD

**Issue by callmeberzerker** [L-Mario564/drizzle-dbml-generator#5]
I am getting this error and I am unsure if it's due to a custom SQL column `ts_vector` column for full-text search. 

```
TypeError: column.getSQLType is not a function
    at PgGenerator.generateColumn (E:\Projects\denarius\node_modules\.pnpm\drizzle-dbml-generator@0.4.0_@types+pg@8.10.9_pg@8.11.3\node_modules\drizzle-dbml-generator\dist\index.cjs:139:91)
    at PgGenerator.generateTable (E:\Projects\denarius\node_modules\.pnpm\drizzle-dbml-generator@0.4.0_@types+pg@8.10.9_pg@8.11.3\node_modules\drizzle-dbml-generator\dist\index.cjs:172:31)
    at PgGenerator.generate (E:\Projects\denarius\node_modules\.pnpm\drizzle-dbml-generator@0.4.0_@types+pg@8.10.9_pg@8.11.3\node_modules\drizzle-dbml-generator\dist\index.cjs:284:35)
    at pgGenerate (E:\Projects\denarius\node_modules\.pnpm\drizzle-dbml-generator@0.4.0_@types+pg@8.10.9_pg@8.11.3\node_modules\drizzle-dbml-generator\dist\index.cjs:328:68)  
    at <anonymous> (e:\Projects\denarius\bin\scripts\db\dbml.ts:10:1)
    at ModuleJob.run (node:internal/modules/esm/module_job:217:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async loadESM (node:internal/process/esm_loader:34:7)
    at async handleMainPromise (node:internal/modules/run_main:66:12)
```

Here is the function where it errs out and the `column` parameter to the function is `object` in some cases and `function() { return new SQL([this])` in the instance where it crashes. (no `getSQLType()` on that function)

```
generateColumn(column) {
    const dbml = new DBML().tab().escapeSpaces(column.name).insert(" ").escapeType(column.getSQLType());
    const constraints = [];
    if (column.primary) {
      constraints.push("pk");
    }
    if (column.notNull) {
      constraints.push("not null");
    }
    if (column.isUnique) {
      constraints.push("unique");
    }
    if (this.isIncremental(column)) {
      constraints.push("increment");
    }
    if (column.default !== void 0) {
      constraints.push(`default: ${this.mapDefaultValue(column.default)}`);
    }
    if (constraints.length > 0) {
      dbml.insert(` [${formatList(constraints, this.buildQueryConfig.escapeName)}]`);
    }
    return dbml.build();
  }
```

**Comment by callmeberzerker** [comment]
I poked around and added the following snippet at that `generateColumn(column)` method.

```js
  // had to bind `this` to the column since it uses `return new SQL([this])`
  generateColumn(column) {
    if (typeof column === "function") {
      console.log('we are here');
      const res = column.call(this)
      console.log(res);
    }
```

The output is:

```
SQL {
  decoder: { mapFromDriverValue: [Function: mapFromDriverValue] },
  shouldInlineParams: false,
  queryChunks: [
    PgGenerator {
      schema: [Object],
      relational: false,
      generatedRefs: [Array],
      InlineForeignKeys: Symbol(drizzle:PgInlineForeignKeys),
      buildQueryConfig: [Object]
    }
  ]
}
```

**Comment by L-Mario564** [comment]
> I am getting this error and I am unsure if it's due to a custom SQL column ts_vector column for full-text search.

May I see how you defined that column and how you use it in a table?

**Comment by callmeberzerker** [comment]
I was mistaken that it is `ts_vector` column. This is something else - and it happens only with the latest drizzle-orm which is ridden with bugs.
